server:
  port: 7002

spring:
  application:
    name: user-service-consumer-feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

# 开启Feign断路器支持
feign.hystrix.enabled: true
