server:
  port: 7002

spring:
  application:
    name: user-service-consumer-feign
  # 服务链路追踪
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

# 开启Feign断路器支持
feign.hystrix.enabled: true

# 开放Hystrix监控界面
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"