server:
  port: 7001

spring:
  application:
    name: user-service-consumer-ribbon
  # 服务链路追踪
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
