server:
  port: 8001

spring:
  application:
    name: user-service-provider
  zipkin:
    base-url: http://localhost:9411/
eureka:
  client:
    serviceUrl:
      # 注册到注册中心;
      defaultZone: http://localhost:9002/eureka/